pills/11-garbage-collector.xml
pills/11/channel-update.txt
pills/11/install-bsd-games.txt
pills/11/ls-gcroots-auto.txt
pills/11/nix-collect-garbage.txt
pills/11/remove-bsd-games.txt
pills/11/remove-gen-9.txt

The only thing I am unsure about is the last paragraph of "Cleanup everything" mentions "Finally, the `-d` option of `nix-collect-garbage` ...". I used a `<command>` tag to wrap `-d`. If you can think of something better, let me know and I can change it.

Port pill #11

---

pills/14-override-design-pattern.xml

We used the wrong code fragment.

Fix code block in Pill 14

---

pills/02-install-on-your-running.xml

Elaborate note about multi-user installations

---

pills/02-install-on-your-running.xml
pills/02/add-user-chown.txt
pills/02/extract-as-nix.txt

Fix installation and download sections

---

pills/01-why-you-should-give-it-try.xml

I thought I'd have a go at going through the pills to make them a little more stylistically formal (since they're now at least semi-official), and improve the clarity in a few places. I've aimed to leave the content largely unchanged.
I've just done the first one to see if it's desirable - if so I'll have a look at doing the others too.

Pill 1: edit for style and clarity

---

pills/01-why-you-should-give-it-try.xml

Nix pill 1: address feedback on #25

---

pills/02-install-on-your-running.xml
pills/03-enter-environment.xml
pills/04-basics-of-language.xml

More in the vein of https://github.com/NixOS/nix-pills/pull/25.

Pills 2-4: edit for style and clarity

---

book.xml
default.nix
pills/19-fundamentals-of-stdenv.xml
pills/20-basic-dependencies-and-hooks.xml
pills/20/build-inputs-0.bash
pills/20/build-inputs-1.bash
pills/20/build-inputs-2.bash
pills/20/build-inputs-3.bash
pills/20/env-hooks-0.bash
pills/20/env-hooks-1.bash
pills/20/propagated-build-inputs-0.bash
pills/20/propagated-build-inputs-1.bash
pills/20/propagated-build-inputs-3.bash
pills/20/setup-hooks-0.bash
pills/20/three-hellos.nix
pills/20/two-hellos.nix

Pill 20: Init according 19's teaser

---

pills/18-nix-store-paths.xml
pills/18/derivation-simple-content.xml
pills/18/derivation-simple-contents.txt

The "pp-aterm" was missed while porting this pill from blogpost.com.

fix last pp-aterm instance

---

README.md

Update README.md with headings and published URL

---

pills/08/hello-builder.txt
pills/08/hello-nix.txt

fix binutils input in hello-builder

---

pills/06-our-first-derivation.xml
pills/15-nix-search-paths.xml

"they can be multiple ones"  seems very strange to me, "there ..." feels nicer.

Fixed typos in 6th and 15th pill

---

pills/03-enter-environment.xml
pills/03/install-hello.txt
pills/04-basics-of-language.xml
pills/07-working-derivation.xml

Suggesting a few tiny changes that might make things clearer for novice nix users.

Miscellaneous minor clarifications

---

pills/04-basics-of-language.xml
pills/04/basics.txt
pills/04/division.txt
pills/04/relative-path.txt
pills/08-generic-builders.xml
pills/09-automatic-runtime.xml
pills/10-developing-with-nix-shell.xml
pills/10/autotools-nix.txt
pills/10/builder-sh.txt
pills/10/hello-nix.txt
pills/10/setup-sh.txt

Can now divide using /<space>

---

pills/18-nix-store-paths.xml

Fixes https://github.com/NixOS/nix-pills/issues/109

update broken link

---

pills/05-functions-and-imports.xml

It's the modern thing, and the docs look nicer too.

Point to Python 3 docs

---

pills/03-enter-environment.xml

Spelling fix for learned.

---

pills/17-nixpkgs-overriding-packages.xml

Tell the reader to recall, not that the author recalls...

17: Use imperative voice

---

pills/08-generic-builders.xml
pills/12-inputs-design-pattern.xml

Fix two typos

---

pills/06-our-first-derivation.xml

Fix typo in pill 6

---

pills/06-our-first-derivation.xml
pills/08-generic-builders.xml
pills/09-automatic-runtime.xml
pills/10-developing-with-nix-shell.xml
pills/11-garbage-collector.xml
pills/12-inputs-design-pattern.xml

Im really enjoying these pills, and just wanted to make some grammar suggestions. I broke them out to a commit per pill.
Tested that the pages rendered ok using the suggestion nix-build command

Grammar suggestions for pills 6-12

---

pills/12-inputs-design-pattern.xml

Probably some text editor madness going on here

Add missing word

---

pills/09-automatic-runtime.xml

Just to unlock CI for https://github.com/NixOS/nix-pills/pull/142 :(

Paraphrase utility of strip

---

pills/12-inputs-design-pattern.xml

See
https://lethalman.blogspot.com/2014/08/nix-pill-12-inputs-design-pattern.html
for original post on which the correction is based.

Add missing beginning of sentence

---

pills/13-callpackage-design-pattern.xml

I believe the previous word order is incorrect

Pill 13: Reorder words so sentence makes more sense

---

pills/09-automatic-runtime.xml

Fixes: https://github.com/NixOS/nixpkgs/issues/34745

Remove one-click install reference

---

pills/08-generic-builders.xml

Checked with `linkchecker --config=<(echo '[AnchorCheck]') --check-extern result/share/doc/nix-pills/*.html`

Fix another broken link

---

pills/08/autotools-nix.txt
pills/08/hello-builder.txt
pills/08/hello-nix-rev-1.txt
pills/08/hello-nix.txt
pills/10/autotools-nix.txt

Fixes #43 & some related issues.

Fix some code samples referring to binutils

---

README.md
default.nix
release.nix

You can get it by running `nix-build release.nix -A pills.epub`.
Fixes: https://github.com/NixOS/nix-pills/issues/31

build: Add EPUB support

---

pills/06-our-first-derivation.xml

A few typos and grammar corrections. Happy to adjust as needed.

Fix typos in pill 6: 'Our First Derivation'

---

pills/09-automatic-runtime.xml

Tiny change on pill 9 - fixing broken link to patchelf.

updated patchelf link to github
