NixOS/nix-pills

- pills/02-install-on-your-running.xml
We pretty much drop the existing instructions in favour of
instructions that can be found on the site.
The current instructions are not only outdated but link to
resources that are no longer available.
> Update installation instructions

- pills/03-enter-environment.xml
- pills/03/nix-store-tree.txt
In current NixOS 17.09,
Current version of `nix-store` command does not accept command as possible one:
```shell
$ nix-store -qR --tree $(command -s man)
error: query type ‘--tree’ conflicts with earlier flag
Try ‘nix-store --help’ for more information.
```
So, `--tree` and `-R` are mutually exclusive options. 
```shell
$ nix-store -q --tree (command -s nix-store)                                                                                                                                                   (1)
/nix/store/b8xy8bdxh1r5yjda332qrxj1vvvsy4fq-nix-1.11.15
+---/nix/store/xzx1bv1d7z4mgg6sg6ly0jx609qvka4x-glibc-2.25-49
|   +---/nix/store/xzx1bv1d7z4mgg6sg6ly0jx609qvka4x-glibc-2.25-49 [...]
+---/nix/store/gpbdiwg2mg21kppj12y019is5r0f8cgn-sqlite-3.20.0
| …
```
> 03: nix-store: --tree and -R are mutually exclusive

- pills/03-enter-environment.xml
I changed the wording from "delete" to "uninstall" to match the official documentation. I also think uninstall makes more sense because of how nix manages package and dependencies.
> 03: fix dead links uninstall/upgrade, change word

- pills/07-working-derivation.xml
- pills/07/c-program-derivation.xml
- pills/08-generic-builders.xml
- pills/08/hello-builder.txt
Add 2, missing closing braces/parens, and move script name out of script to the text above it.
> A few small fixes to braces and filename placement

- pills/08-generic-builders.xml
- pills/08/hello-builder.txt
- pills/08/hello-nix-rev-1.txt
- pills/08/hello-nix-rev-2.txt
- pills/08/hello-nix.txt
- pills/09/instantiate.txt
- pills/10-developing-with-nix-shell.xml
- pills/19/hello-derivation.txt
- pills/19/stdenv-hello.txt
- pills/19/stdenv-setup-fake-builder.txt
I was just going through the pills and found the GNU Hello version was one behind. This PR updates pill 8 to use the latest GNU Hello.
> Update GNU Hello version to 2.10

- pills/08/autotools-nix.txt
- pills/08/hello-builder.txt
- pills/08/hello-nix-rev-1.txt
- pills/08/hello-nix.txt
`binutils` is missing `ar` causing the compilation of GNU hello to fail, switching to `binutils-unwrapped` corrects the issue as this has `ar` in the environment.
> Pill 8: Fix missing ar binary in build environment

- pills/04-basics-of-language.xml
Add a missing `e` to `Howver` in the section describing `let/in` expressions.
> Fix typo in "Basics of Language" chapter

- pills/04/set-recursive.txt
Minor update adding a space for consistency with the formatting of the other examples in this section.
> Add missing space in recursive attributes example

- pills/15-nix-search-paths.xml
attributes vs names is confusing to new users, attributes graphiz and graphizCore both have names graphiz, so you MUST use the attribute to avoid ambiguity
> may -> must as attribute is required to avoid ambiguity

- pills/07-working-derivation.xml
Hi,
my first intuition was to name the file ``main.c`` and I was curious whether this was right. It could have been another sane "default" but its not. I believe this helps the novice.
> Pill 07: Make the input file name explicit.

- pills/08-generic-builders.xml
- style.css
This takes advantage of existing styling support.
> Nix on darwin note: use a `<note>` element

- pills/18-nix-store-paths.xml
There seams to be a typo in the path of the included file: https://nixos.org/nixos/nix-pills/nix-store-paths.html#idm140737315515840
`derivation-simple-contents.xml -> derivation-simple-content.xml`
> pill 18.1: Fix filename typo

- pills/03-enter-environment.xml
The word `your` does not seem to make sense.
> Fixed typo in 03-enter-environment.xml

- pills/02-install-on-your-running.xml
- pills/02/profile.xml
- pills/02/user-environment.xml
- pills/03-enter-environment.xml
- pills/03/install-hello.txt
- pills/03/install-repl.txt
- pills/03/install.txt
- pills/03/list-installed-derivations.txt
- pills/03/ls-nix-profile.txt
- pills/03/ls-profile-bin.txt
- pills/03/nix-env-rollback.txt
- pills/03/references.txt
- pills/03/referrers.txt
- pills/03/uninstall-all.txt
- pills/04-basics-of-language.xml
- pills/05-functions-and-imports.xml
- pills/06-our-first-derivation.xml
- pills/07-working-derivation.xml
- pills/12-inputs-design-pattern.xml
- pills/12/repository-test-nix-repl.txt
- pills/14-override-design-pattern.xml
- pills/14/nix-repl-make-overridable-test.txt
- pills/16/config-foo-bar.txt
- pills/18/derivation-simple.txt
In #89 it has been reported that the third step can't be done as
`nix-repl` doesn't evaluate anymore on 18.09 and unstable as in both
cases an evaluation error will be thrown.
First of all this may confuse new users who want to learn Nix, but don't
know the ecosystem sufficiently to understand why the install failed.
As recent NixOS versions (unstable and 18.09) use Nix 2.0 by default and
unstable doesn't evaluate with Nix 1.x anymore it should be a safe thing
to do now.
This patch covers two aspects:
* Using Nix 2.0: I replayed the installation steps with `nix-env` to
ensure that the steps and explanations provided in the first three
chapters are still valid.
* Replacing `nix-repl` references: most of the cases it was sufficient
to replace `nix-repl` with the newly introduced command …
> Update documentation after Nix 2.0 switch

- pills/04-basics-of-language.xml
- pills/04/set-basics.txt
The attribute name is quoted correctly by the REPL in nix 2.1.3:
```
⟫ nix repl                    
Welcome to Nix version 2.1.3. Type :? for help.
nix-repl> s = { foo = "bar"; a-b = "baz"; "123" = "num"; }
nix-repl> s
{ "123" = "num"; a-b = "baz"; foo = "bar"; }
nix-repl>
```
> Update Attribute sets example and remove obsolete note

- pills/02-install-on-your-running.xml
Just a small typo-fix: "next pill" link previous linked back to pill 2. I tested this by running
```
nix-build release.nix && firefox result/share/doc/nix-pills/index.html
```
and verifying that the link ended up pointing to the right place.
> Fix erroneous link in pill 2

- pills/08-generic-builders.xml
Previously, the screen being outside the para would prevent it from
being displayed.
> 08: Fix display of darwin-specific code

- pills/04-basics-of-language.xml
I think the for is unnecessary and can be confusing (at least for me).
> Change sentence wording in 04-basics-of-language

- pills/20/propagated-build-inputs-0.bash
ensureDir was dropped with the merge of https://github.com/NixOS/nixpkgs/pull/33637
> change ensureDir to mkdir -p in example

- pills/08-generic-builders.xml
`stdenv` has not yet been mentioned in this tutorial and the target audience (people new to nix) will not know what it is.  It shouldn't be mentioned until it is properly described (as it is in pill 19).
> remove stdenv references

- pills/02-install-on-your-running.xml
I came across this when trying to install on a fresh VPS instance. The `-L` flag was necessary to get it to work.
For reference, here is the (request elided) response part when running `curl https://nixos.org/nix/install --verbose`
```
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 150)!
< HTTP/2 301
< age: 21
< content-length: 0
< date: Thu, 10 Sep 2020 08:15:30 GMT
< location: https://releases.nixos.org/nix/nix-2.3.7/install
< server: Netlify
< via: 1.1 42f9f0e9bd0296c3bb45648019b2dce5.cloudfront.net (CloudFront)
< x-amz-cf-id: KnFHvob-NJ_lChDqqK4tnjrWyo2fo_FOoSkLrcsOYyrBXz4mLdsWkQ==
< x-amz-cf-pop: LAX3-C3
< x-cache: Hit from …
```
> Follow redirects when installing via `curl`

- pills/03-enter-environment.xml
The install command `nix-env -i man` does not work as `man` is the
*attribute name* meanwhile the command expects the derivation name which
is `man-db`. If using the attribute name then the command should use the
`{--attr | -A}` option and pass the attribute path, e.g.:
`nix-env -iA nixpkgs.man`.
> Change install arg from `man` to `man-db`

- pills/08-generic-builders.xml
The previous link leads to the top of the guide whereas the updated link
leads to Section *15.3 Operators* where one can quickly find the row in
the table that presents the `//` operator.
> Update link for the `//` operator

- pills/10-developing-with-nix-shell.xml
Since `setup.sh` is a new addition, it makes more sense to not use the
word "modified", as it did not exist before :).
> Re-word "modified setup.sh" in pill 10

- pills/01-why-you-should-give-it-try.xml
- pills/02-install-on-your-running.xml
- pills/03-enter-environment.xml
- pills/04-basics-of-language.xml
- pills/05-functions-and-imports.xml
- pills/06-our-first-derivation.xml
- pills/07-working-derivation.xml
- pills/09-automatic-runtime.xml
- pills/10-developing-with-nix-shell.xml
- pills/11-garbage-collector.xml
- pills/12-inputs-design-pattern.xml
- pills/13-callpackage-design-pattern.xml
- pills/15-nix-search-paths.xml
- pills/18-nix-store-paths.xml
I was following the nix pills, but since https://github.com/NixOS/nix/pull/3857, all links to the nix manual are broken (as mentioned in #152).
I replaced every link with the equivalent in the new manual structure.
Supersedes #152, #176.
> Update links to new nix manual structure

- pills/12-inputs-design-pattern.xml
- pills/12/graphviz-derivation.txt
- pills/12/graphviz-gd-derivation.txt
- pills/12/graphviz-mkderivation.txt
- pills/12/repository-mkderivation.txt
- pills/12/setup-sh.txt
This also fixes https://github.com/NixOS/nix-pills/issues/107
`graphviz`'s configure script respects the output of `pkg-config` if this tool's env vars are set correctly, so PNG does work with this change.
> Fix pill 12 derivations so that PNG support works

- pills/11-garbage-collector.xml
This was removed in 2013 from nix v1.6. Don't point readers of the
pills towards a link that no longer is there.
fixes #105
> update GC pill to not mention gcroots/profiles

- pills/04/let-scope.txt
If a user follows along in the repl, the error won't occur as in section 4.6 the number 4 is assigned to `b`. To make this slightly less confusing and have the error appear as the user is following along we have to use a new variable.
> `b` is already defined in section 4.7 if the user follows along in the repl

- pills/13-callpackage-design-pattern.xml
In pill 13 `callPackage` and `pkgs` are defined co-recursively. The
author notes thas this is possible due to lazy evaluation, but for some
readers this may be confusing (as if lazy evaluation was some kind of
magic that makes infinite recursion not a problem).
> Clarify how lazy evaluation helps to escape infinite co-recursion.

- pills/16-nixpkgs-parameters.xml
- pills/17-nixpkgs-overriding-packages.xml
* Fix [link to config.nix](https://github.com/NixOS/nixpkgs/blob/32c523914fdb8bf9cc7912b1eba023a8daaae2e8/pkgs/top-level/impure.nix#L28) in source, and update the path to ~/.config/nixpkgs/config.nix. Link to today's permalink at github instead of master. When this was originally written, ~/.nixpkgs/config.nix was loaded by all-packages.nix. But this was moved to pkgs/top-level/default.nix (https://github.com/NixOS/nixpkgs/commit/ad317834053983e1bf3b61f58c923ca48a0dd2d7 ) and then to pkgs/top-level/impure.nix (https://github.com/NixOS/nixpkgs/commit/4af2bf66631d187d952b70fba4963e33002d1dcb)
* Fix [link to fix function](https://github.com/NixOS/nixpkgs/blob/f224a4f1b32b3e813783d22de54e231cd8ea2448/lib/fixed-points.nix#L19) in nixpkgs source. Link to today's permalink at github instead of …
> Fix links to nixpkgs source

- pills/17-nixpkgs-overriding-packages.xml
In 2815ca0fab63b1a93be6417ff77822e530c4ddfe (#197) I accidentally changed a config.nix link (which I fixed in the previous commit ddd0a63dac83f766a63e10096eabb7b85024654c) to point to the `fix` definition instead. This commit reverts that part of the commit. Sorry.
> Fix link to reference to config.nix again

- pills/07-working-derivation.xml
- pills/07/read-log.xml
- pills/07/simple-derivation.xml
Instead nix-store --read-log can be used to see the environment variables.
This commit fixes #106.
> Output of declare -xp is no longer visible in the repl

- pills/08-generic-builders.xml
> Use HTTPS links in 8th pill

- pills/08/hello-nix-darwin.txt
The Darwin nix still assigns to `binutils`, even though the builder itself was updated to point to `bintools` in ce931b9697343dc781b004834c496edd28b52186. Fixing this ensures the hello example actually builds on Darwin.
> Pill 8: fix Darwin reference to binutils

- pills/17/config-nix.txt
- pills/17/graphviz-override.txt
- pills/17/p-graphviz-override.txt
In the current version of nix, overriding `xorg = null;` no longer seems to work; overriding the `withXorg` attribute allowed it to pass for me instead.
> Pill 17: fix graphviz xorg override

- pills/17-nixpkgs-overriding-packages.xml
- pills/17/build-asciidoc-graphviz-override.txt
Attempting to build this as specified in the current docs fails with the error:
```
nix-repl> :b pkgs.asciidocFull
error: 'asciidocFull' has been renamed to/replaced by 'asciidoc-full'
```
> Pill 17: fix asciidoc-full name

- pills/20/three-hellos.nix
- pills/20/two-hellos.nix
As written, this produces a script without the execute bit set, which may confuse users who want to try actually running it after building.
> Pill 20: allow wrapped hello to be executed

- pills/02-install-on-your-running.xml
Instead refering to original link which links to the Nix manual.
This pull request is related to #202 and also https://github.com/NixOS/nix.dev/issues/424
There is more work to do to change pill 2, but this can hopefully be a start.
> removing installation instructions

- pills/07-working-derivation.xml
- pills/07/simple.txt
- pills/07/simple_inherit.txt
Nix example file no longer starts with with (import <nixpkgs> {});
It's an attempt to better follow style guidelines for how to write nix expressions.
> with removed from first line

- pills/08-generic-builders.xml
- pills/08/autotools-nix.txt
- pills/08/hello-builder.txt
- pills/08/hello-nix-darwin.txt
- pills/08/hello-nix-rev-1.txt
- pills/08/hello-nix-rev-2.txt
- pills/08/hello-nix.txt
This is a general refresh of the pill, including using the with statements with a smaller scope (better practice)
What I know is not 100%:
~~The naming - mymkDerivation - I wanted to avoid collision and confusion with with pkgs.stdenv.mkDerivation.~~
~~The Darwin part - I haven't tested those adaptions as I am on WSL.~~
> Pill 8 update

- pills/19-fundamentals-of-stdenv.xml
- tense corrections e.g. "did dive" -> "dived"
- pluralisation corrections
- "is not a special derivation to Nix" -> "is not treated as a special derivation by Nix"
- add question marks to headings phrased as questions, or transform them into statements
- sentence separation and removal of semicolons
- adverb corrections e.g. "enough contained" -> "sufficiently contained"
- links to sources in GitHub where they felt frustratingly missing
> Grammatical adjustments to Nix Pill 19

- pills/08-generic-builders.xml
Hi,
In Conclusion of pill 08 `mymkDerivation` is mentioned as a function that was created. I believe it should be changed to `mkDerivation` - that's the name declared in code [here](https://github.com/NixOS/nix-pills/blob/master/pills/08/hello-nix-rev-2.txt#L3C3-L3C15):
```nix
mkDerivation = import ./autotools.nix pkgs;
```
Also, `mkDerivation`  is mentioned earlier in the pill [here](https://github.com/NixOS/nix-pills/blob/master/pills/08-generic-builders.xml#L266)
> fix(typo): rename mymkDerivation to mkDerivation in Conclusion of pill 08

- pills/07-working-derivation.xml
Closes #221 
Two choices were made:
* explaining that derivations coming from `<nixpkgs>` have to be referred to as members of the set assigned to local variable `pkgs`;
* skipping any explanation about the use of the `with` keyword, although it would be the one-to-one equivalent of what was done in the REPL.
Edits allowed.
> Solve a discrepancy in pill 7.7

- pills/06/examine-build.xml
- pills/06/show-derivation.xml
- pills/07/foo.drv.xml
- pills/18/bar-derivation.xml
- pills/18/derivation-simple-content.xml
- pills/19/hello-derivation.xml
It looks like the command `nix show-derivation` is deprecated in favor of `nix derivation show` .
This replaces all instances of `show-derivation` with `derivation show`
> show-derivation -> derivation show

- pills/02-install-on-your-running.xml
Replacing with nix.dev language basics link.
(not a 100% substitute)
Trying to address  #226 but of course open for other suggestions as well.
> removing broken link for writing expressions

- pills/09-automatic-runtime.xml
- pills/10-developing-with-nix-shell.xml
- pills/11-garbage-collector.xml
- pills/12-inputs-design-pattern.xml
- pills/13-callpackage-design-pattern.xml
- pills/14-override-design-pattern.xml
This PR (and future PRs I'll be submitting in the same vein) is focused on improving grammar, voicing, stylistic consistency, and readability. As a relatively inexperienced Nix user, I don't have much to add in terms of content or technical commentary; I'd simply like to improve the quality of the existing documentation.
I've found that the earlier pills have a slightly different tone than the later pills -- some of which almost seems like it can be attributed to different authors -- and that the writing style becomes weaker as the material grows in complexity. As such, I only committed to undertaking this editing starting at pill #9 (the point at which I felt my own comprehension beginning to suffer), and I plan on editing as I go through the remaining pills. Once I'm finished, I'll try …
> Non-content edits to pills 9-14

- pills/07-working-derivation.md
When switching from the nix repl to a nix file, `derivation` was replaced with `pkgs.stdenv.mkDerivation`. This was not explained, and the examples work fine without this. It seems to me that when learning that you can define the derivation in a nix file instead of in the repl, there's no need to add another change.
I see that the next chapter uses plain `derivation` in the first examples, and then defines a new function `mkDerivation`. So I'm pretty certain that we should just use plain `derivation` here.
> 07-working-derivation.md: use `derivation` instead of `mkDerivation`

- pills/00-preface.md
As far as I can tell, that was dropped in 926e878dceeddf95efd34079256bf127f09b77f6
> preface: Remove mention of root prompt

- pills/09-automatic-runtime-dependencies.md
The link to NixOps was corrupted by mistake in this PR: https://github.com/NixOS/nix-pills/pull/181/files#diff-a53cbc0f08ac225fd5073d54147a9a6ba2ebbdbd0e5164711ab362d0439cc27aR265
It was changed by mistake from http://nixos.org/nixops/manual/#chap-introduction to https://nixos.org/manual/nix/stable/introduction.html.
I think that at least for now, it would be better to link to https://github.com/NixOS/nixops, as the old link just links to an obscure in-development HTML document, and the github link starts with a warning "NixOps is in low-maintenance mode and probably not suited for new projects. Use at your own risks", and also links to an experimental NixOps4.
> Update 09-automatic-runtime-dependencies.md - fix NixOps link

- pills/07-working-derivation.md
The text says that `builder.sh` is in the input derivations. It's actually in `inputSrcs`, not `inputDrvs`. Perhaps in the past there was just one list?
> Update 07-working-derivation.md - "input derivations" -> "input sources"

- pills/01-why-you-should-give-it-a-try.md
- pills/03-enter-environment.md
We have an official wiki now, so updating wiki links to it.
> replace unoffical wiki links with offical ones

- pills/02-install-on-your-running-system.md
- pills/03-enter-environment.md
- pills/04-basics-of-language.md
- pills/05-functions-and-imports.md
- pills/06-our-first-derivation.md
- pills/07-working-derivation.md
- pills/08-generic-builders.md
- pills/10-developing-with-nix-shell.md
- pills/11-garbage-collector.md
- pills/13-callpackage-design-pattern.md
- pills/15-nix-search-paths.md
- pills/18-nix-store-paths.md
This patch fixes some issues with links to the Nix manual.
Fixes:
- Broken links are replaced with working ones to equivalent pages
- Replace old manual domain (nixos.org) with nix.dev to avoid to be redirected
> Fix and update links to Nix manual

- pills/13-callpackage-design-pattern.md
Removed the 'a' from 
"we would likely want to bundle that package derivation into a repository via **_a_** an attribute set defined as something like:"
> Fixed minor typo in pill 13

- pills/15-nix-search-paths.md
Enclose command option -I in backticks to avoid confusion between uppercase I and lowercase l.
> Add backticks to command options for clarity

- pills/07-working-derivation.md
My setup required the inclusion of the stdio headers. 
I have little experience with C, so that caught me first time. 
By the way, I also had to change the filename of my C script, since it seems that Nix caches the files after the first compilation and I haven't found how to easily refresh the cache with `nix repl`. So, It could be cool to also include this in the docs.
> [Fix]: add missing stdio header
